---
title: "Graphic Design with ggplot2"
subtitle: "<span style='font-size:1.75em;line-height:1.1;'>Concepts of the <code>{ggplot2}</code> Package Pt. 2:<br><span style='font-weight:500;'>Exercise 2</span></span>"
author: "<b style='color:#28a87d;'>Cédric Scherer</b> **//** rstudio::conf **//** July 2022"
format: 
  revealjs: 
    theme: css/style.scss
    footer: '**[Cédric Scherer](https::/cedricscherer.com) //** rstudio::conf **//** July 2022'
    #'rstudio::conf(workshop = "Graphic Design with ggplot2", instructor = "Cédric Scherer")'
    transition: fade
    progress: true
    multiplex: false
    preview-links: true
    scrollable: false
    hide-inactive-cursor: true
    highlight-style: printing
    chalkboard:
      theme: whiteboard
      boardmarker-width: 4
      buttons: true
    pause: true
    mainfont: Cabinet Grotesk
editor: visual
knitr:
  opts_chunk: 
    dev: "ragg_png"
    retina: 1
    dpi: 300
execute:
  freeze: auto
  echo: true
  fig-width: 5
  fig-height: 6.05
---


## Your Turn!

::: question
* Create a circular lollipop plot of reported bike shares per season. 
  - The data is not in the right format as there are no totals.<br>How can you solve it?
  - Remove all legend elements (with a single line of code).
  - How can you add the labels next to the starting point of each lollipop?
  - How could you add a baseline?
:::

```{r}
#| label: countdown
#| echo: false
countdown::countdown(minutes = 30, font_size = ".5em")
```



##  {background-image="3-2-circular-lollipop/concepts-pt2-exercise-2-1-1.png" background-position="center" background-size="45%"}



##  {background-image="3-2-circular-lollipop/concepts-pt2-exercise-2-2-1.png" background-position="center" background-size="45%"}



##  {background-image="3-2-circular-lollipop/concepts-pt2-exercise-2-3-1.png" background-position="center" background-size="45%"}



##  {background-image="3-2-circular-lollipop/concepts-pt2-exercise-2-4-1.png" background-position="center" background-size="45%"}



##  {background-image="3-2-circular-lollipop/concepts-pt2-exercise-2-5-1.png" background-position="center" background-size="45%"}



##  {background-image="3-2-circular-lollipop/concepts-pt2-exercise-2-6-1.png" background-position="center" background-size="45%"}



##  {background-image="3-2-circular-lollipop/concepts-pt2-exercise-2-7-1.png" background-position="center" background-size="45%"}




##  {background-image="img/exercise-what-now.png" background-position="center" background-size="45%"}
