---
title: "Graphic Design with ggplot2"
subtitle: "Concepts of the <code>{ggplot2}</code> Package Pt. 2: Astronaut Viz Exercise 1"
author: "Cédric Scherer"
format: html
editor: source
knitr:
  opts_chunk: 
    dev: "ragg_png"
    retina: 1
    dpi: 300
execute:
  freeze: auto
  echo: true
  warning: false
  message: false
---

```{r}
#| label: import-data-exercise
library(tidyverse)

df_astro <- readr::read_csv(
  'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv'
)

df_missions <-
  df_astro %>% 
  group_by(name) %>% 
  summarize(
    hours = sum(hours_mission),
    year = min(year_of_mission),
    max_year = max(year_of_mission)
  ) %>% 
  ungroup() %>% 
  mutate(year = -year) %>% 
  arrange(year) %>% 
  mutate(id = row_number())
```


```{r}
#| label: astronaut-viz-blank
#| fig-width: 15
#| fig-height: 15
g <- 
  ggplot(
      df_missions,
      aes(x = id, y = hours, color = hours)
    ) +
    ## curves
    geom_linerange(
      aes(
        ymin = 0, ymax = hours,
        alpha = hours
      ),
      size = .25
    )  +
    ## baseline
    geom_point(
      aes(y = 0),  
      shape = 15, size = .1, color = "#808080"
    ) +
    ## points
    geom_point(
      aes(y = hours, size = hours)
    ) +
    coord_polar(theta = "y", start = 0, clip = "off") +
    scale_x_continuous(limits = c(-300, NA), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 23000), expand = c(0, 0)) +
    #scale_color_viridis_c(option = "cividis", begin = .15) +
    scale_color_distiller(palette = "YlGnBu", direction = -1) +
    scale_size(range = c(.001, 3)) +
    scale_alpha(range = c(.33, .95)) +
    theme_void() +
    theme(
      plot.background = element_rect(fill = "black"),
      plot.margin = margin(-70, -70, -70, -70),
      legend.position = "none"
    )

# g
# 
# ggsave(
#   here::here("slides", "plots", "outerspace-rstudioconf-blank-brewer.pdf"), 
#   width = 15, height = 15, device = cairo_pdf
# )
# 
# g_imola <- g +
#   scico::scale_color_scico(palette = "buda", end = .95) ## nuuk; imola
# 
# ggsave(
#   here::here("slides", "plots", "outerspace-rstudioconf-blank-imola.pdf"), 
#   width = 15, height = 15, device = cairo_pdf
# )
```


```{r}
#| label: astronaut-viz-labels
#| fig-width: 15
#| fig-height: 15
df_labs <- 
  df_missions %>% 
  filter(year %in% -c(1961, 197:201*10, 2019)) %>% 
  group_by(year) %>% 
  filter(id == min(id))

df_max <-
  df_missions %>% 
  arrange(-hours) %>% 
  slice(1) %>% 
  mutate(
    first_name = str_remove(name, ".*, "),
    last_name = str_remove(name, "(?<=),.*"),
    label = paste("Between", abs(year), "and", max_year, ",\n", first_name, last_name, "has spent\n", format(hours, big.mark = ','), "hours in space.\nThat's roughly", round(hours / 24, 0), "days!")
  ) 

g_labs <- 
   g +
    ## labels years
    geom_text(
      data = df_labs,
      aes(y = 0, label = abs(year)),
      family = "Roboto Condensed", fontface = "bold", color = "#808080",
      size = 4.5, hjust = 1.2
    ) +
    ## label max
    geom_text(
      data = df_max, aes(label = label),
      family = "Roboto Condensed", size = 3.9, vjust = -.35
    ) +
    ## title shadow
    annotate(
      geom = "text", x = -300, y = 0, 
      label = "Travelling to\nOuter Space", 
      family = "Boska", fontface = "bold", lineheight = .9,
      size = 20, color = "white", hjust = .57, vjust = .45, alpha = .25
    ) +
    ## title 
    annotate(
      geom = "text", x = -300, y = 0, 
      label = "Travelling to\nOuter Space", 
      family = "Boska", fontface = "bold", lineheight = .85,
      size = 20, color = "white", hjust = .55, vjust = .4
    ) +
    labs(caption = "Cumulative time in outer space for all 565 cosmonauts and astronauts who participated\nin space missions between April 23, 1961 and January 15, 2020, sorted by the year of their first mission.\n\nGraphic: Cédric Scherer • Data: Stavnichuk & Corlett 2020 (DOI: 10.17632/86tsnnbv2w.1)") +
    theme(
      plot.caption = element_text(
        family = "Roboto Condensed", 
        size = 15, color = "#808080", hjust = .5,
        margin = margin(-100, 0, 100, 0)
      )
    )

g_labs

ggsave(
  here::here("slides", "plots", "03_concepts_pt2_ex1_astronaut_brewer.pdf"), 
  width = 15, height = 16, device = cairo_pdf
)

g_labs +
  scico::scale_color_scico(palette = "buda", end = .95) ## nuuk; imola

ggsave(
  here::here("slides", "plots", "03_concepts_pt2_ex1_astronaut_buda.pdf"), 
  width = 15, height = 16, device = cairo_pdf
)
```


```{r}
#| label: convert-pdfs
#| include: false
path <- here::here("slides", "plots")
pdfs <- list.files(path, pattern = "*buda.pdf|*brewer.pdf", recursive = TRUE)
for(pdf in pdfs) {
  pdftools::pdf_convert(
    pdf = glue::glue("{path}/{pdf}"), 
    filenames = glue::glue("{path}/{str_remove(pdf, '.pdf')}.png"),
    format = "png", dpi = 300
  )
}
```
