---
title: "Graphic Design with ggplot2"
subtitle: "Concepts of the <code>{ggplot2}</code> Package Pt. 2: Circular Lollipop Exercise 2"
author: "Cédric Scherer"
format: html
editor: visual
knitr:
  opts_chunk: 
    dev: "ragg_png"
    retina: 1
    dpi: 300
execute:
  freeze: auto
  echo: true
  fig-width: 5
  fig-height: 6.05
  warning: false
  message: false
---


```{r}
#| label: prep
#| echo: false
library(tidyverse)

bikes <- readr::read_csv(
  "https://raw.githubusercontent.com/z3tt/graphic-design-ggplot2/main/data/london-bikes-custom.csv", 
  col_types = "Dcfffilllddddc"
)

bikes$season <- forcats::fct_inorder(bikes$season)

theme_set(theme_light(base_size = 14, base_family = "Roboto Condensed"))
```

```{r}
#| label: concepts-pt2-exercise-2-1
#| echo: false
#| fig-width: 8
#| fig-height: 8
#| fig-align: "center"
ggplot(bikes, aes(x = season, y = count)) +
  stat_summary(geom = "point", fun = "sum", size = 3) +
  stat_summary(geom = "linerange", ymin = 0, fun.max = function(y) sum(y)) +
  scale_y_continuous(limits = c(0, NA))
```

```{r}
#| label: concepts-pt2-exercise-2-2
#| echo: false
#| fig-width: 8
#| fig-height: 8
#| fig-align: "center"
ggplot(bikes, aes(x = season, y = count)) +
  stat_summary(geom = "point", fun = "sum", size = 3) +
  stat_summary(geom = "linerange", ymin = 0, fun.max = function(y) sum(y)) +
  coord_polar(theta = "y") +
  scale_y_continuous(limits = c(0, NA))
```

```{r}
#| label: concepts-pt2-exercise-2-3
#| echo: false
#| fig-width: 8
#| fig-height: 8
#| fig-align: "center"
ggplot(bikes, aes(x = season, y = count)) +
  stat_summary(geom = "point", fun = "sum", size = 3) +
  stat_summary(geom = "linerange", ymin = 0, fun.max = function(y) sum(y)) +
  coord_polar(theta = "y") +
  scale_x_discrete(expand = c(.5, .5)) +
  scale_y_continuous(limits = c(0, 7.5*10^6)) 
```

```{r}
#| label: concepts-pt2-exercise-2-4
#| echo: false
#| fig-width: 8
#| fig-height: 8
#| fig-align: "center"
ggplot(bikes, aes(x = season, y = count)) +
  stat_summary(geom = "point", fun = "sum", size = 3) +
  stat_summary(geom = "linerange", ymin = 0, fun.max = function(y) sum(y)) +
  coord_polar(theta = "y") +
  scale_x_discrete(expand = c(.5, .5)) +
  scale_y_continuous(limits = c(0, 7.5*10^6)) +
  theme_void()
```

```{r}
#| label: concepts-pt2-exercise-2-5
#| echo: false
#| fig-width: 8
#| fig-height: 8
#| fig-align: "center"
ggplot(bikes, aes(x = season, y = count)) +
  stat_summary(geom = "point", fun = "sum", size = 3) +
  stat_summary(geom = "linerange", ymin = 0, fun.max = function(y) sum(y)) +
  coord_polar(theta = "y") +
  scale_x_discrete(expand = c(.5, .5)) +
  scale_y_continuous(limits = c(0, 7.5*10^6)) +
  theme_void() +
  theme(plot.margin = margin(rep(-130, 4)))
```

```{r}
#| label: concepts-pt2-exercise-2-6
#| echo: false
#| fig-width: 8
#| fig-height: 8
#| fig-align: "center"
ggplot(bikes, aes(x = season, y = count)) +
  stat_summary(geom = "point", fun = "sum", size = 3) +
  stat_summary(geom = "linerange", ymin = 0, fun.max = function(y) sum(y)) +
  stat_summary(
    geom = "text", aes(label = stringr::str_to_title(season), y = 0), 
    family = "Cabinet Grotesk", fontface = "bold", size = 4.5, hjust = 1.15
  ) +
  coord_polar(theta = "y") +
  scale_x_discrete(expand = c(.5, .5)) +
  scale_y_continuous(limits = c(0, 7.5*10^6)) +
  theme_void() +
  theme(plot.margin = margin(rep(-130, 4)))
```

```{r}
#| label: concepts-pt2-exercise-2-7
#| echo: false
#| fig-width: 8
#| fig-height: 8
#| fig-align: "center"
ggplot(bikes, aes(x = as.numeric(season), y = count, group = season)) +
  stat_summary(geom = "point", fun = "sum", size = 3) +
  stat_summary(geom = "linerange", ymin = 0, fun.max = function(y) sum(y)) +
  stat_summary(
    geom = "text", aes(label = stringr::str_to_title(season), y = 0), 
    family = "Cabinet Grotesk", fontface = "bold", size = 4.5, hjust = 1.15
  ) +
  annotate(
    geom = "linerange", xmin = .7, xmax = 4.3, y = 0
  ) +
  coord_polar(theta = "y") +
  scale_x_discrete(expand = c(.5, .5)) +
  scale_y_continuous(limits = c(0, 7.5*10^6)) +
  theme_void() +
  theme(plot.margin = margin(rep(-130, 4)))
```
